/**
 * Clustering result persistence.
 *
 * After a clustering UDTF SELECT succeeds, the webapp is responsible for
 * writing the per-record rows to CORTEX_TESTING.PUBLIC.CLUSTERING_RESULTS
 * (the UDTFs return rows but do not INSERT them — the stored procedures used
 * to, but those have been replaced by UDTFs for SQL-API compatibility).
 *
 * Rows are batched in groups of 500 to stay within Snowflake statement size
 * limits.  Persistence failures are non-fatal — the caller catches and logs.
 *
 * SQL injection prevention: every value goes through escapeStr / escapeNum
 * which apply Snowflake's single-quote doubling rule.  Snowflake does NOT
 * treat backslash as an escape character in default single-quoted string
 * literals, so '' (two single quotes) is the only escaping required.
 */

import { executeSQL } from './sql-api';
import { SNOWFLAKE_ROLE } from './cortex-agent-api';

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const PERSIST_TABLE = 'CORTEX_TESTING.PUBLIC.CLUSTERING_RESULTS';

/** Number of rows per INSERT batch — keeps the statement below Snowflake limits */
const BATCH_SIZE = 500;

// ---------------------------------------------------------------------------
// Escape helpers
// ---------------------------------------------------------------------------

/**
 * Wrap a value in a SQL single-quoted string literal, escaping internal
 * single-quotes by doubling them.  Returns NULL for null / undefined.
 */
function escapeStr(val: unknown): string {
  if (val === null || val === undefined) return 'NULL';
  return `'${String(val).replace(/'/g, "''")}'`;
}

/**
 * Emit a SQL numeric literal, or NULL if the value is not a finite number.
 */
function escapeNum(val: unknown): string {
  if (val === null || val === undefined) return 'NULL';
  const n = Number(val);
  return isFinite(n) ? String(n) : 'NULL';
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export interface ClusterPersistMeta {
  /** Webapp user / session identifiers added to every row */
  userId: string;
  sessionId: string;
  /** Optional: Snowflake query ID of the UDTF SELECT (from the execution) */
  queryId?: string;
  /** Run-level identifiers generated by the webapp (not returned by the UDTF) */
  runId: string;
  runTimestamp: string;     // ISO-8601 string, e.g. new Date().toISOString()
  algorithm: string;        // e.g. 'KMEANS', 'DBSCAN', 'GM', 'HIERARCHICAL', 'KMEDOIDS'
  nSegmentsRequested: number;
  nSegmentsUsed: number;
}

/**
 * Persist clustering UDTF result rows to CORTEX_TESTING.PUBLIC.CLUSTERING_RESULTS.
 *
 * @param rows     Raw rows returned by executeSQL() — Record<columnName, value>.
 *                 Expected UDTF columns: RUN_ID, RUN_TIMESTAMP, ALGORITHM,
 *                 N_SEGMENTS_REQUESTED, N_SEGMENTS_USED, RECORD_ID, CLUSTER_ID,
 *                 CLUSTER_LABEL, CLUSTER_PROBABILITY, CLUSTER_ENTROPY, PC1, PC2,
 *                 MODEL_METADATA, FEATURE_ZSCORES.
 * @param meta     Session-level metadata added by the webapp.
 * @param signal   Optional AbortSignal — batches stop if aborted.
 */
export async function persistClusteringResults(
  rows: Record<string, unknown>[],
  meta: ClusterPersistMeta,
  signal?: AbortSignal,
): Promise<void> {
  if (!rows.length) return;

  /**
   * Column accessor: tries uppercase then lowercase key so this works
   * regardless of whether executeSQL returns column names in their
   * original case or normalised to uppercase.
   */
  const col = (row: Record<string, unknown>, name: string): unknown =>
    row[name] ?? row[name.toUpperCase()] ?? row[name.toLowerCase()] ?? null;

  // Split into batches
  const batches: Record<string, unknown>[][] = [];
  for (let i = 0; i < rows.length; i += BATCH_SIZE) {
    batches.push(rows.slice(i, i + BATCH_SIZE));
  }

  let totalInserted = 0;

  for (const batch of batches) {
    if (signal?.aborted) break;

    const valuesList = batch
      .map((r) => {
        return (
          `(\n` +
          [
            escapeStr(meta.runId),
            escapeStr(meta.runTimestamp),
            escapeStr(meta.userId),
            escapeStr(meta.sessionId),
            escapeStr(meta.queryId ?? null),
            escapeStr(meta.algorithm),
            escapeNum(meta.nSegmentsRequested),
            escapeNum(meta.nSegmentsUsed),
            escapeStr(col(r, 'RECORD_ID')),
            escapeNum(col(r, 'CLUSTER_ID')),
            escapeStr(col(r, 'CLUSTER_LABEL')),
            escapeNum(col(r, 'CLUSTER_PROBABILITY')),
            escapeNum(col(r, 'CLUSTER_ENTROPY')),
            escapeNum(col(r, 'PC1')),
            escapeNum(col(r, 'PC2')),
            escapeStr(col(r, 'MODEL_METADATA')),
            escapeStr(col(r, 'FEATURE_ZSCORES')),
          ].join(', ') +
          `\n)`
        );
      })
      .join(',\n');

    const insertSQL = `
INSERT INTO ${PERSIST_TABLE}
  (RUN_ID, RUN_TIMESTAMP, USER_NAME, SESSION_ID, QUERY_ID, ALGORITHM,
   N_SEGMENTS_REQUESTED, N_SEGMENTS_USED, RECORD_ID, CLUSTER_ID,
   CLUSTER_LABEL, CLUSTER_PROBABILITY, CLUSTER_ENTROPY, PC1, PC2,
   MODEL_METADATA, FEATURE_ZSCORES)
VALUES
${valuesList}`;

    await executeSQL(insertSQL, SNOWFLAKE_ROLE, signal);
    totalInserted += batch.length;
    console.log(`[CLUSTER_PERSIST] Inserted batch ${batches.indexOf(batch) + 1}/${batches.length} (${batch.length} rows)`);
  }

  console.log(`[CLUSTER_PERSIST] Done — ${totalInserted}/${rows.length} rows written to ${PERSIST_TABLE}`);
}
