/**
 * All agent, pipeline, dispatch, and core types for SRIntelligence.
 */

import type { UserPreferences } from './user';

// ---------------------------------------------------------------------------
// Intent union
// ---------------------------------------------------------------------------

export type AgentIntent =
  | 'ANALYST'
  | 'FORECAST_PROPHET'
  | 'FORECAST_SARIMA'
  | 'FORECAST_HW'
  | 'FORECAST_XGB'
  | 'FORECAST_COMPARE'
  | 'FORECAST_AUTO'
  | 'MTREE'
  | 'CLUSTER'
  | 'PIPELINE'
  | 'UNKNOWN';

// ---------------------------------------------------------------------------
// Semantic view
// ---------------------------------------------------------------------------

export interface SemanticViewRef {
  id: string;
  displayName: string;
  description: string;
  /** Fully-qualified view name as stored in Snowflake, e.g. DB.SCHEMA.VIEW */
  fullyQualifiedName: string;
  allowedRoles: string[];
  isDefault: boolean;
  tags: string[];
}

// ---------------------------------------------------------------------------
// Conversation
// ---------------------------------------------------------------------------

export interface ConversationMessage {
  id: string;
  role: 'user' | 'assistant' | 'system';
  content: string;
  timestamp: number;
  intent?: AgentIntent;
  /** Optional reference to the artifact produced in this turn */
  artifactId?: string;
}

// ---------------------------------------------------------------------------
// Cost tracking
// ---------------------------------------------------------------------------

export interface CostEstimate {
  inputTokens: number;
  outputTokens: number;
  /** USD */
  estimatedCostUsd: number;
  model: string;
}

// ---------------------------------------------------------------------------
// Agent artifacts and results
// ---------------------------------------------------------------------------

export type CacheStatus = 'hit' | 'miss' | 'bypassed' | 'error';

export interface AgentArtifact {
  id: string;
  agentName: string;
  intent: AgentIntent;
  /** Raw structured data returned by the agent */
  data: unknown;
  /** SQL generated by the agent, if applicable */
  sql?: string;
  /** Human-readable narrative summary */
  narrative?: string;
  createdAt: number;
  /** Lineage tracking identifier linking this artifact to upstream executions */
  lineageId: string;
  cacheStatus: CacheStatus;
  costEstimate?: CostEstimate;
}

export interface AgentResult {
  success: boolean;
  artifact?: AgentArtifact;
  error?: string;
  /** Wall-clock duration in milliseconds */
  durationMs: number;
  retryCount: number;
}

// ---------------------------------------------------------------------------
// Agent input
// ---------------------------------------------------------------------------

export interface AgentInput {
  message: string;
  intent: AgentIntent;
  sessionId: string;
  userId: string;
  semanticView: SemanticViewRef;
  conversationHistory: ConversationMessage[];
  userPreferences: UserPreferences;
  /** Additional key-value context passed through from the orchestrator */
  extraContext?: Record<string, unknown>;
}

// ---------------------------------------------------------------------------
// Agent context (execution-time state)
// ---------------------------------------------------------------------------

export interface AgentContext {
  sessionId: string;
  userId: string;
  userRole: string;
  semanticView: SemanticViewRef;
  conversationHistory: ConversationMessage[];
  userPreferences: UserPreferences;
  /** Accumulated cost across all agents in this context */
  totalCostEstimate: CostEstimate;
  /** Map of agentName → AgentResult for previously executed agents in this pipeline */
  priorResults: Map<string, AgentResult>;
  startedAt: number;
}

// ---------------------------------------------------------------------------
// Retry
// ---------------------------------------------------------------------------

export interface RetryConfig {
  maxAttempts: number;
  /** Base delay in milliseconds for exponential backoff */
  baseDelayMs: number;
  /** Maximum delay cap in milliseconds */
  maxDelayMs: number;
  /** HTTP status codes that should trigger a retry */
  retryableStatusCodes: number[];
}

// ---------------------------------------------------------------------------
// Pipeline
// ---------------------------------------------------------------------------

export interface PipelineStep {
  /** Unique step identifier within the pipeline */
  stepId: string;
  intent: AgentIntent;
  agentName: string;
  description: string;
  /** Step IDs that must complete before this step can run */
  dependsOn: string[];
  /** Whether failure of this step should abort the entire pipeline */
  required: boolean;
  retryConfig?: RetryConfig;
  /** Arbitrary parameters forwarded to the agent */
  params?: Record<string, unknown>;
}

export interface PipelineDefinition {
  id: string;
  name: string;
  description: string;
  steps: PipelineStep[];
  /** Whether steps without dependencies can run in parallel */
  parallelizable: boolean;
  createdAt: number;
  /** User-visible label, used in narrative synthesis */
  semanticViewDisplayName: string;
}

// ---------------------------------------------------------------------------
// Streaming / dispatch events
// ---------------------------------------------------------------------------

export type PipelineEventType =
  | 'STEP_START'
  | 'STEP_COMPLETE'
  | 'STEP_ERROR'
  | 'PIPELINE_START'
  | 'PIPELINE_COMPLETE'
  | 'PIPELINE_ERROR';

export interface PipelineEvent {
  type: PipelineEventType;
  pipelineId: string;
  stepId?: string;
  agentName?: string;
  timestamp: number;
  payload?: unknown;
}

export type DispatchEventType =
  | 'ROUTING'
  | 'AGENT_START'
  | 'AGENT_COMPLETE'
  | 'AGENT_ERROR'
  | 'SYNTHESIS_START'
  | 'SYNTHESIS_COMPLETE'
  | 'ERROR';

export interface DispatchEvent {
  type: DispatchEventType;
  sessionId: string;
  userId: string;
  timestamp: number;
  intent?: AgentIntent;
  agentName?: string;
  payload?: unknown;
  error?: string;
}

// ---------------------------------------------------------------------------
// Formatted response (what the API layer returns to the client)
// ---------------------------------------------------------------------------

export interface FormattedResponse {
  id: string;
  sessionId: string;
  intent: AgentIntent;
  /** Markdown narrative for display */
  narrative: string;
  /** Individual agent artifacts, in execution order */
  artifacts: AgentArtifact[];
  /** Suggested follow-up questions */
  suggestions: string[];
  totalCostEstimate: CostEstimate;
  durationMs: number;
  /** Lineage ID that ties this response to its execution chain */
  lineageId: string;
  createdAt: number;
}
